In [14]:
import pandas as pd
import numpy as np

import utils.plot_utils as plot_utils

In [15]:
# settings
dim = 128

In [16]:
# load results
df = pd.read_csv(
    "./twitter_alpha-0.1_beta-0.1_ws-10_neg-5_lr-0.025_icom-62_ind-62_k-7_ds-0.0.txt",
    sep="\t",
    header=None,
    names=["X"]
)

# load labels
labels = pd.read_csv(
    "./twitter.labels",
    sep="\t",
    header=None,
    names=["y"]
)

In [17]:
# split dimensions
df = df.join(df["X"].str.split(" ", n = dim, expand = True), rsuffix="x")

# join labels
df = df.join(labels)

# rename columns 
df = df.rename(columns=dict((i, "x"+str(i)) for i in range(dim)))

# set types
for i in range(dim):
    df["x"+ str(i)] = df["x" + str(i)].astype(float)
df["y"] = df["y"].astype(int)

In [18]:
display(df.describe())
display(df.head())

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x119,x120,x121,x122,x123,x124,x125,x126,x127,y
count,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,...,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000,2495.000000
mean,-0.003426,0.016186,0.065990,-0.014828,-0.076577,-0.086639,-0.218740,0.138812,-0.113184,0.066334,...,-0.121646,0.094339,-0.148275,0.004147,-0.066680,-0.169048,0.138123,-0.074414,-0.007614,2.211222
std,0.169097,0.161021,0.184505,0.216362,0.178914,0.176171,0.176588,0.182890,0.176091,0.183509,...,0.183377,0.170623,0.170522,0.177520,0.173258,0.189928,0.176759,0.172447,0.183743,1.707769
min,-0.732130,-0.591775,-0.551990,-0.716685,-0.720105,-0.887054,-0.888449,-1.048470,-0.776151,-0.556029,...,-0.720420,-0.631360,-0.795542,-0.870517,-0.806891,-1.090250,-0.569424,-0.687826,-0.603834,0.000000
25%,-0.115907,-0.077195,-0.042719,-0.156542,-0.190081,-0.204732,-0.328844,0.031556,-0.222424,-0.046701,...,-0.248079,-0.014866,-0.255394,-0.100264,-0.178506,-0.291844,0.021075,-0.188901,-0.127147,2.000000
50%,-0.004440,0.017718,0.063293,-0.036155,-0.081118,-0.078851,-0.226807,0.145722,-0.111556,0.065030,...,-0.130637,0.092343,-0.150344,0.007132,-0.055232,-0.155669,0.137563,-0.090337,-0.008625,2.000000
75%,0.109134,0.114580,0.171264,0.102948,0.034063,0.028075,-0.111113,0.256323,-0.006249,0.178086,...,-0.001544,0.200670,-0.043439,0.116249,0.050311,-0.041951,0.251926,0.021101,0.105914,2.000000
max,0.562654,0.733451,0.907785,1.280270,0.801861,0.667443,0.451765,0.756711,0.592890,1.133910,...,0.660219,0.797449,0.573828,0.732008,0.503389,0.429929,1.034480,0.597657,0.657334,7.000000

,X,x0,x1,x2,x3,x4,x5,x6,x7,x8,...,x119,x120,x121,x122,x123,x124,x125,x126,x127,y
0,0.277659 -0.0262274 0.222251 -0.172726 0.09640...,0.277659,-0.026227,0.222251,-0.172726,0.096405,-0.279529,-0.316456,0.251455,-0.284306,...,-0.079947,0.425723,-0.179571,0.227779,0.157605,-0.184389,0.093946,-0.076616,-0.131611,6
1,0.0097469 0.156903 0.283129 0.163562 -0.265943...,0.009747,0.156903,0.283129,0.163562,-0.265943,-0.500880,-0.743025,-0.151343,0.103389,...,0.309457,-0.090620,-0.192812,-0.118362,-0.220180,-0.209450,0.404455,-0.203548,-0.129572,4
2,0.0682189 0.117238 0.0532579 -0.267467 -0.1983...,0.068219,0.117238,0.053258,-0.267467,-0.198346,-0.067206,-0.023660,0.324613,-0.406977,...,-0.076259,-0.111987,-0.282293,-0.154044,0.132923,0.429929,0.310655,-0.021396,-0.066769,6
3,0.157139 -0.0976129 0.356484 -0.187756 -0.0891...,0.157139,-0.097613,0.356484,-0.187756,-0.089176,0.139785,-0.256427,0.357987,-0.118927,...,-0.148033,-0.152798,-0.270251,-0.151964,-0.106687,-0.108819,0.469479,-0.151912,0.253865,2
4,0.111357 -0.0166892 -0.114175 -0.134582 -0.039...,0.111357,-0.016689,-0.114175,-0.134582,-0.039351,-0.073751,-0.191715,0.329307,-0.194676,...,-0.167635,0.168904,-0.137436,-0.027380,-0.145663,-0.026866,0.174114,-0.338619,-0.144811,5

# plot all Xs in 2D
for i in range(dim):
    for j in range(dim):
        df.plot(x="x"+str(i), y="x"+str(j), c="y", kind="scatter", colormap='gist_rainbow')

# plot 10 random Xs in 2d
for _ in range(10):
    i, j = np.random.choice(dim, 2)
    df.plot(x="x"+str(i), y="x"+str(j), c="y", kind="scatter", colormap='gist_rainbow')

In [ ]:
# plot using plot_utils